### ISSUE TITLE
Could this wrapper be used with NetlifyCMS?

### ISSUE THREAD

**Issue by jinman** [TimothyJones/github-cognito-openid-wrapper#12]
Netlify CMS uses Github to store documents. It has Git Gateway to authenticate it to Git providers. I am wondering whether if we have a web app that is authenticated via Cognito as the identity provider to use NetlifyCMS, do we have to configure git-gateway to use this openid-wrapper? Has anyone tried this before?

**Comment by TimothyJones** [comment]
I haven't done this (I'm not familiar with Netlify or Git Gateway), but a quick scan of [the docs]( https://www.netlify.com/docs/identity/) suggests that Netlify exposes OAuth2 endpoints. This means you could do:

`Your Site -> Cognito -> OpenID to OAuth Shim -> Netlify Identity -> Git Gateway -> GitHub`

Where `OpenID to OAuth Shim` was a modified version of this repository. Let me know if you'd like pointers on how to do this.

It's probably easier to do

`Your Site -> Netlify Identity -> Git Gateway -> GitHub`

If you can.

**Comment by jinman** [comment]
My apologies. I was referring to NetlifyCMS [1] (and not Netlify service). NetlifyCMS is a open source CMS (React SPA that uses github as the store). I would like to use Cognito so Cognito's user pool users can automatically leverage NetlifyCMS. Since NetlifyCMS requires Github login, their docs say to install [Node-based OAUTH Clients](https://www.netlifycms.org/docs/authentication-backends/#external-oauth-clients). I was wondering whether your wrapper can help with this (via OpenID)?

[1] https://www.youtube.com/watch?v=p6h-rYSVX90

**Comment by TimothyJones** [comment]
Ah, thanks for the clarification. I think I understand now.

I think the short answer is maybe, but I think it will take some development work. I think you have to modify both one of the OAuth clients and this repository.

NetlifyCMS's external provider code looks like a modification of OAuth2, where instead of returning a token in the response, you need to do a `postMessage` which contains the GitHub token, targeting the React SPA as a response - [the key part is here](https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/index.js#L72). Because of this message handling system, you'd have to wrap Cognito in your own external provider shim.

Now, Cognito exposes [OpenID endpoints](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html). Since OAuth2 is a subset of OpenID, you would be able to use Cognito in place of GitHub in one of NetlifyCMS external provider clients. This means "your own external provider shim" could just be a modified version of one of the OAuth clients you linked.  

However, this wouldn't be enough - the token that Cognito will give NetlifyCMS will be generated by Cognito, which means NetlifyCMS can't use it to access GitHub. The flow looks like this:

`<---Cognito Token---  [COGNITO] <---GitHub Token--- [GITHUB SHIM] <--- GitHub Token --- [GITHUB]`

So, you'd need to pass the GitHub token through the shim to Cognito. I think you could do this by implementing a custom claim in the `/userinfo` that contains the GitHub token.

`<---GitHub Token--- [Another Shim] <---Cognito Token---  [COGNITO] <---GitHub Token--- [GITHUB SHIM] <--- GitHub Token --- [GITHUB]`

1. Modify [this line](https://github.com/TimothyJones/github-cognito-openid-wrapper/blob/master/src/openid.js#L43)
```
-  ]).then(claims => claims.reduce((acc, claim) => ({ ...acc, ...claim }), {}));
+  ]).then(claims => claims.reduce((acc, claim) => ({ ...acc, ...claim }), { accessToken }));
```
2. Specify a [custom attribute mapping](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-specifying-attribute-mapping.html) for the github shim that maps `accessToken` to a custom attribute

3. Modify the OAuth2 client that wraps Cognito to use the Congito token to read the userinfo endpoint on Cognito. This will now contain the GitHub access token, which you can return it to your app ([Here is where I would start](https://github.com/vencax/netlify-cms-github-oauth-provider/blob/master/index.js#L64) if I were modifying the node shim).

4. Use this new shim as the auth for your NetlifyCMS.

You may run into trouble with different expiry times on the GitHub tokens and Cognito tokens. And, I'm not sure if it's safe to store the users github tokens in your user pool (it means that anyone compromising your pool would have access to the github accounts).

There's probably a better way.

**Comment by TimothyJones** [comment]
This repository is for identity federation with GitHub. This means that in the design I've written out above (and if you're using this shim at all), then you are creating users in your user pool every time anyone logs in with GitHub. This may not be what you want - especially if you're wanting to use an existing user pool.

Another design that you could consider is modifying one of the OAuth clients to have the following behaviour:

1. Redirect to Cognito
2. Have a new `/cognitoCallback` endpoint that redirects to github if the Cognito login was successful.
2. Use the existing `/callback` endpoint to obtain the github token and return it.

This means your users would have to log in twice (Cognito and then GitHub), but it means you wouldn't be storing GitHub credentials anywhere, and you could use your existing user pool users.

In this scenario (probably better, depending on your needs), you wouldn't need `github-cognito-openid-wrapper`.

Hopefully all of the above makes sense! Please feel free to ask followup questions.

**Comment by jinman** [comment]
Thank you very much for the detailed explanation. Now I understand it more clearly. I feel the second solution above might make more sense as once the cognito user has logged in from the existing set of user pool users and once it is successful, we somehow figure it out to store github credentials (one github user for userpool users) and store it somewhere in Lambda code and use that to authenticate to Github behind the scene to pass it back to NetlifyCMS as we cannot have users to login twice. Is there anyway we could use this repository to get the github token and pass it to NetlifyCMS, all after cognito user has been authenticated by both cognito and (common credentials user by) github?

**Comment by TimothyJones** [comment]
I think if you're planning to use:

* Cognito as the login method for users
* A common github user for all logged in users

then this repository probably doesn't help you.

This repository converts GitHub's OAuth to OpenID for GitHub's [web flow](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow). This means that users who are directed to this shim would be redirected to the login page for your common github user. This is probably not what you want.

Instead I would take a look at GitHub's [non-web application flow](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#non-web-application-flow) for authentication.

I think you could build a custom login shim for NetlifyCMS that directed the user to Cognito, and then (if login was successful) used GitHub's non-web application flow to obtain the GitHub credentials.

Since this isn't really about this code any more, I'll close this issue. Please feel free to reopen it if you need further help from me.
