### ISSUE TITLE
github accounts with 2FA fail

### ISSUE THREAD

**Issue by DannyDouglass** [TimothyJones/github-cognito-openid-wrapper#27]
@TimothyJones greetings! first off, thanks for the hard work on open sourcing this repo. I'm interested in providing support after getting a working example up and running in quick time thanks to this repo (i'll connect with a proposal i'm building in the near future). 

in the meantime...one issue i'm running into is that github users with two-factor authentication enabled are unable to sign in. this is the result after entering (correct) credentials into the cognito-initiated github auth flow:

![image](https://user-images.githubusercontent.com/266481/71703104-dffdab80-2d87-11ea-875d-7c8814d94342.png)
i've verified with a different github user account with two-factor disabled, and things work as expected. i already have our cognito user pool working with google, but this is my first attempt at an openid cognito provider.

have you run into this issue before? i've been digging most of the day, however have not had much luck. thanks in advance for any help you can offer!

**Comment by TimothyJones** [comment]
I believe it's a bug with either Cognito or GitHub, but I wasn't able to determine which. It's described in Issue #24.

It's possible to work around it with a bit of extra infrastructure (described in #24), but it's hard to provide a general recommendation that works for all loads, and since adding a Dynamo DB table is a fair bit of extra work (and potentially operational costs that not everyone will need), I haven't been able to merge it in to this repo yet.

**Comment by TimothyJones** [comment]
I'm going to close this in favour of keeping discussion over at #24 - please feel free to add your thoughts there.

**Comment by DannyDouglass** [comment]
thanks for the quick response @TimothyJones - i'll take a look at the issue and fork in more detail tomorrow. i'd like to contribute back to this repo as i think it's a very valuable resource. appreciate your time.
